export const PRODUCTS_REQUESTED = 'PRODUCTS_REQUESTED';
export const PRODUCTS_LOADED = 'PRODUCTS_LOADED';
export const PRODUCTS_FAILURE = 'PRODUCTS_FAILURE';

export const CATEGORIES_REQUESTED = 'CATEGORIES_REQUESTED';
export const CATEGORIES_LOADED = 'CATEGORIES_LOADED';
export const CATEGORIES_FAILURE = 'CATEGORIES_FAILURE';

export const SET_FILTERS = 'SET_FILTERS';
export const USER_DATA_LOADED = 'USER_DATA_LOADED';
export const RESET_USER_DATA = 'RESET_USER_DATA';

export const CART_ITEMS_REQUESTED = 'CART_ITEMS_REQUESTED';
export const CART_ITEMS_LOADED = 'CART_ITEMS_LOADED';
export const CART_ITEMS_FAILURE = 'CART_ITEMS_FAILURE';

export const ADD_PRODUCT_TO_CART_REQUESTED = 'ADD_PRODUCT_TO_CART_REQUESTED';
export const ADD_PRODUCT_TO_CART_SUCCESS = 'ADD_PRODUCT_TO_CART_SUCCESS';
export const ADD_PRODUCT_TO_CART_FAILURE = 'ADD_PRODUCT_TO_CART_FAILURE';

export const REMOVE_PRODUCT_FROM_CART_REQUESTED = 'REMOVE_PRODUCT_FROM_CART_REQUESTED';
export const REMOVE_PRODUCT_FROM_CART_SUCCESS = 'REMOVE_PRODUCT_FROM_CART_SUCCESS';
export const REMOVE_PRODUCT_FROM_CART_FAILURE = 'REMOVE_PRODUCT_FROM_CART_FAILURE';

export const ALL_PRODUCTS_REMOVED_FROM_CART_REQUESTED = 'ALL_PRODUCTS_REMOVED_FROM_CART_REQUESTED';
export const ALL_PRODUCTS_REMOVED_FROM_CART_SUCCESS = 'ALL_PRODUCTS_REMOVED_FROM_CART_SUCCESS';
export const ALL_PRODUCTS_REMOVED_FROM_CART_FAILURE = 'ALL_PRODUCTS_REMOVED_FROM_CART_FAILURE';