export const PRODUCTS_REQUESTED = 'PRODUCTS_REQUESTED';
export const PRODUCTS_LOADED = 'PRODUCTS_LOADED';
export const PRODUCTS_FAILURE = 'PRODUCTS_FAILURE';

export const CATEGORIES_REQUESTED = 'CATEGORIES_REQUESTED';
export const CATEGORIES_LOADED = 'CATEGORIES_LOADED';
export const CATEGORIES_FAILURE = 'CATEGORIES_FAILURE';

export const USER_DATA_REQUESTED = 'USER_DATA_REQUESTED';
export const USER_DATA_LOADED = 'USER_DATA_LOADED';
export const USER_DATA_FAILURE = 'USER_DATA_FAILURE';
export const RESET_USER_DATA = 'RESET_USER_DATA';

export const CART_ITEMS_REQUESTED = 'CART_ITEMS_REQUESTED';
export const CART_ITEMS_LOADED = 'CART_ITEMS_LOADED';
export const CART_ITEMS_FAILURE = 'CART_ITEMS_FAILURE';

export const ADD_PRODUCT_TO_CART_REQUESTED = 'ADD_PRODUCT_TO_CART_REQUESTED';
export const ADD_PRODUCT_TO_CART_SUCCESS = 'ADD_PRODUCT_TO_CART_SUCCESS';
export const ADD_PRODUCT_TO_CART_FAILURE = 'ADD_PRODUCT_TO_CART_FAILURE';

export const REMOVE_PRODUCT_FROM_CART_REQUESTED = 'REMOVE_PRODUCT_FROM_CART_REQUESTED';
export const REMOVE_PRODUCT_FROM_CART_SUCCESS = 'REMOVE_PRODUCT_FROM_CART_SUCCESS';
export const REMOVE_PRODUCT_FROM_CART_FAILURE = 'REMOVE_PRODUCT_FROM_CART_FAILURE';

export const ALL_PRODUCTS_REMOVED_FROM_CART_REQUESTED = 'ALL_PRODUCTS_REMOVED_FROM_CART_REQUESTED';
export const ALL_PRODUCTS_REMOVED_FROM_CART_SUCCESS = 'ALL_PRODUCTS_REMOVED_FROM_CART_SUCCESS';
export const ALL_PRODUCTS_REMOVED_FROM_CART_FAILURE = 'ALL_PRODUCTS_REMOVED_FROM_CART_FAILURE';

export const DETAILS_REQUESTED = 'DETAILS_REQUESTED';
export const DETAILS_LOADED = 'DETAILS_LOADED';
export const DETAILS_FAILURE = 'DETAILS_FAILURE';

export const ADD_DETAIL_REQUESTED = 'ADD_DETAIL_REQUESTED';
export const ADD_DETAIL_SUCCESS = 'ADD_DETAIL_SUCCESS';
export const ADD_DETAIL_FAILURE = 'ADD_DETAIL_FAILURE';

export const UPDATE_DETAIL_REQUESTED = 'UPDATE_DETAIL_REQUESTED';
export const UPDATE_DETAIL_SUCCESS = 'UPDATE_DETAIL_SUCCESS';
export const UPDATE_DETAIL_FAILURE = 'UPDATE_DETAIL_FAILURE';

export const REMOVE_DETAIL_REQUESTED = 'REMOVE_DETAIL_REQUESTED';
export const REMOVE_DETAIL_SUCCESS = 'REMOVE_DETAIL_SUCCESS';
export const REMOVE_DETAIL_FAILURE = 'REMOVE_DETAIL_FAILURE';

export const CATEGORIES_LIST_REQUESTED = 'CATEGORIES_LIST_REQUESTED';
export const CATEGORIES_LIST_SUCCESS = 'CATEGORIES_LIST_SUCCESS';
export const CATEGORIES_LIST_FAILURE = 'CATEGORIES_LIST_FAILURE';

export const ADD_CATEGORY_REQUESTED = 'ADD_CATEGORY_REQUESTED';
export const ADD_CATEGORY_SUCCESS = 'ADD_CATEGORY_SUCCESS';
export const ADD_CATEGORY_FAILURE = 'ADD_CATEGORY_FAILURE';

export const UPDATE_CATEGORY_REQUESTED = 'UPDATE_CATEGORY_REQUESTED';
export const UPDATE_CATEGORY_SUCCESS = 'UPDATE_CATEGORY_SUCCESS';
export const UPDATE_CATEGORY_FAILURE = 'UPDATE_CATEGORY_FAILURE';

export const REMOVE_CATEGORY_REQUESTED = 'REMOVE_CATEGORY_REQUESTED';
export const REMOVE_CATEGORY_SUCCESS = 'REMOVE_CATEGORY_SUCCESS';
export const REMOVE_CATEGORY_FAILURE = 'REMOVE_CATEGORY_FAILURE';

export const PRODUCTS_LIST_REQUESTED = 'PRODUCTS_LIST_REQUESTED';
export const PRODUCTS_LIST_SUCCESS = 'PRODUCTS_LIST_SUCCESS';
export const PRODUCTS_LIST_FAILURE = 'PRODUCTS_LIST_FAILURE';

export const ADD_PRODUCT_REQUESTED = 'ADD_PRODUCT_REQUESTED';
export const ADD_PRODUCT_SUCCESS = 'ADD_PRODUCT_SUCCESS';
export const ADD_PRODUCT_FAILURE = 'ADD_PRODUCT_FAILURE';

export const UPDATE_PRODUCT_REQUESTED = 'UPDATE_PRODUCT_REQUESTED';
export const UPDATE_PRODUCT_SUCCESS = 'UPDATE_PRODUCT_SUCCESS';
export const UPDATE_PRODUCT_FAILURE = 'UPDATE_PRODUCT_FAILURE';

export const REMOVE_PRODUCT_REQUESTED = 'REMOVE_PRODUCT_REQUESTED';
export const REMOVE_PRODUCT_SUCCESS = 'REMOVE_PRODUCT_SUCCESS';
export const REMOVE_PRODUCT_FAILURE = 'REMOVE_PRODUCT_FAILURE';