export const PRODUCTS_LOADED = 'PRODUCTS_LOADED';
export const CATEGORIES_LOADED = 'CATEGORIES_LOADED';
export const SET_FILTERS = 'SET_FILTERS';
export const USER_DATA_LOADED = 'USER_DATA_LOADED';
export const RESET_USER_DATA = 'RESET_USER_DATA';